favicon: null
name: Sustainable Gardens
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7900108
  brandStrength: 0.9414311063010246
  lightness: 0.6911923
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  rhythmicContrast: 0.7513427
typography_spectrum: 0.08899
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.96983
analytics:
  twitter: null
  google: null
  facebook: null
